services:
  db:
    image: kartoza/postgis:13
    restart: always
    volumes:
      - .:/app
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'password'
      POSTGRES_DB: 'local-intelligence'
      POSTGRES_PORT: 5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -h 127.0.0.1"]
      interval: 5s
      timeout: 5s
      retries: 5
    working_dir: /app
    ports:
      - "53333:5432"
      - "8000:8000"
  web:
    image: mysociety/local-intelligence-hub:${TAG:-latest}
    build: .
    command: /app/script/server --development
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy
    tty: true
    environment:
      SECRET_KEY: 'secret'
      DEBUG: 1
      DATABASE_URL: 'postgis://postgres:password@db/local-intelligence'
      EMAIL_HOST: email.svc
      CACHE_FILE: 'data/cache'
      MAPIT_URL: 'https://mapit.mysociety.org/'
      GOOGLE_ANALYTICS: ${GOOGLE_ANALYTICS:-}
      GOOGLE_SITE_VERIFICATION: ${GOOGLE_SITE_VERIFICATION:-}
      DJANGO_SUPERUSER_USERNAME: 'admin'
      DJANGO_SUPERUSER_PASSWORD: 'password'
      DJANGO_SUPERUSER_EMAIL: 'admin@localhost'
    working_dir: /app
    # Runs app on the same network as the database container,
    # allows "forwardPorts" in devcontainer.json function
    # so that mtxr.sqltools and third party DB clients can access it
    network_mode: service:db
  mailhog:
    image: mailhog/mailhog:v1.0.1
    restart: always
    ports:
      - 1025:1025
      - 8025:8025
    networks:
     default:
       aliases:
         - email.svc

volumes:
  pgdata:
  build:
  node_modules:
