# Generated by Django 4.2.11 on 2024-10-26 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0141_externaldatasource_social_url_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="externaldatasource",
            name="geocoding_hint",
            field=models.CharField(
                blank=True,
                help_text="A hint to help the geocoder understand the data in the address field; for example if all the data is about Glasgow.",
                max_length=250,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="externaldatasource",
            name="include_title_in_address_for_geocoding",
            field=models.BooleanField(
                default=False,
                help_text="Useful when the title field is a business name, and/or the address field is simply a street name.",
            ),
        ),
    ]
