# Generated by Django 4.2.11 on 2025-02-20 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0163_merge_20250214_1409"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="uploadedcsvsource",
            name="columns",
        ),
        migrations.AddField(
            model_name="databasejsonsource",
            name="use_row_number_as_id",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="uploadedcsvsource",
            name="use_row_number_as_id",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="uploadedcsvsource",
            name="id_field",
            field=models.CharField(default="id", max_length=250),
        ),
    ]
