# Run linting and basic file format checks

name: Lint

on:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run black
        uses: psf/black@stable
        with:
          options: "--check --diff"
          src: "."
          version: "24.3.0"
      - name: Run isort
        uses: isort/isort-action@master
      - name: Run flake8
        uses: py-actions/flake8@v2
