# Run linting and basic file format checks

name: Lint

on:
  pull_request:

jobs:
  lint-python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run black
        uses: psf/black@stable
        with:
          options: "--check --diff"
          src: "."
          version: "24.4.2"
      - name: Run isort
        uses: isort/isort-action@master
      - name: Run flake8
        uses: py-actions/flake8@v2

  lint-nextjs:
    defaults:
      run:
        working-directory: ./nextjs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run linters
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - run: npm install
      - run: npm run lint
