name: Run project tests

concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
  
on:
  push:
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2

      - name: Run django tests
        uses: ./.github/actions/in-container
        env:
          DATABASE_URL: postgres://postgres:postgres@postgres/postgres
          CACHE_FILE: /tmp/meep
          SECRET_KEY: keyboardcat
        with:
          run: |
            script/bootstrap
            script/test --coverage

      # do this inside the docker container otherwise the paths don't work
      - name: generate coverage xml
        uses: ./.github/actions/in-container
        with:
          run: coverage xml

      # do this outside the docker container otherwise can't get repo details
      - name: upload code coverage
        run: |
          less coverage.xml
          pip install codecov
          codecov
